### ISSUE TITLE
About Us link issue

### ISSUE THREAD

**Issue by mhoare** [Code-Your-Future/code-your-future-web#42]
The about us link in the header doesn't work when not on the homepage.
The `a.scroll` functionality in `js/scripts.js` is causing an exception on pages where the hash location is not on the current page. 

I am working on a solution

**Comment by apmaros** [comment]
🏆 You are right, thanks for looking into it.

**Comment by mhoare** [comment]
No problem, I have added a pull request to staging and once approved you can merge to master
